### ISSUE TITLE
Sezione 1 - Tecnologie 1

### ISSUE THREAD

**Issue by gianguaz** [AScuolaDiOpencoesione/ASOCFront#14]
Prima di Tecnologie 1 ci vuole il seguente testo descrittivo:

**DOTAZIONI TECNOLOGICHE DELLA SCUOLA (REQUISITI TECNICI NECESSARI PER LA PARTECIPAZIONE AL PROGETTO). Rispondere SI/NO.**

**Comment by chiaracio** [comment]
Sostituire semplice flag con toggle si/no

**Comment by chiaracio** [comment]
Campo "Altre informazioni sulla dotazione tecnologica" aggiungere limite massimo 300 caratteri.

**Comment by sirmmo** [comment]
fatto il limite di testo
