### ISSUE TITLE
Pagina Creazione profilo docente 2

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#21]
Togliere i campi 
http://www.clipular.com/c/6368336954261504.png?k=f-5FmfoKxLYEEFWVgknVnO8VtrU

**Comment by chiaracio** [comment]
sostituire i campi "area" e "interesse" con: 

Area disciplinare (menu a tendina) 
Area Artistica
Area Linguistica
Area Scientifica 
Area Tecnica 

Materia d'insegnamento (campo libero)

**Comment by sirmmo** [comment]
salva/invia aggiunto
