### ISSUE TITLE
Sezione 1 - modificare testo iniziale

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#22]
Fare copincolla del seguente testo mantenendo i capoversi e i grassetti:

Per candidare un gruppo classe al progetto "A Scuola di OpenCoesione" per l'anno scolastico 2016/2017 è necessario compilare e inviare online il presente modulo di candidatura. 
Al termine della compilazione verrà automaticamente inviata copia della candidatura in formato pdf all'indirizzo e-mail indicato in fase di registrazione.  

Il modulo deve essere compilato **a cura del docente referente di progetto** e si riferisce alla candidatura di un solo gruppo classe, che potrà essere costituito da un'intera classe o da un gruppo formato da studenti di classi diverse fino ad un massimo di 30 studenti. Se nella stessa scuola si intende far partecipare più di un gruppo classe, è necessario compilare due moduli differenti.

**Le candidature dovranno pervenire entro le ore 15:00 del 14 ottobre 2016.**

(I campi contrassegnati con *asterisco sono obbligatori)

**Comment by sirmmo** [comment]
fatto
