### ISSUE TITLE
Sezione 2 - Esperienze precedenti in ambito didattico e/o professionale* 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#30]
Spostare il campo "Altro" (specificare) come ultima opzione. 

Aggiungere accanto ad altro un campo di testo libero breve

Spostare su la domanda e sostituire "ha" con "hai" 
Prima di ASOC, hai partecipato o gestito in prima persona altri progetti rilevanti rispetto a temi affini o rilevanti?

cancellare conseguentemente la domanda successiva: "Altre esperienze (in caso di 'Altro' al punto prima)"

**Comment by sirmmo** [comment]
testo modificato.
