### ISSUE TITLE
Sezione 3 - Altro docente referente 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#31]
Modificare campo "Area di insegnamento altro docente referente" come segue 

Area disciplinare altro docente referente (menu a tendina) 
Area Artistica
Area Linguistica
Area Scientifica 
Area Tecnica

Successivamente aggiungere campo: 
Materia d'insegnamento (campo libero)

**Comment by sirmmo** [comment]
cambiato nome campo
