### ISSUE TITLE
Sezione 4 - campo Associazione di supporto

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#34]
Sostituire testo campo come segue. 

testo: Tipo di associazione di supporto (Menu a tendina)

Poi rendere condizionali e obbligatori tutti i campi successivi come da immagine 
http://www.clipular.com/c/6185514960420864.png?k=bvvYK1N-frhhV-e4kiB2zdnpT2o

**Comment by sirmmo** [comment]
Menu a tendina:
Associazione appartenente agli Amici di ASOC
Nuova Associazione

**Comment by sirmmo** [comment]
fatto campo
