### ISSUE TITLE
Pagina platform Home

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#37]
Bottoni fac-simile e vademecum non funzionanti @chiara manda file

**Comment by sirmmo** [comment]
mancano i file. Uso per ora fac simile da mail (i campi sono cambiati...)

**Comment by sirmmo** [comment]
[ASOC1617_Facsimile_formselezione_scuole.pdf](https://github.com/AScuolaDiOpencoesione/ASOCFront/files/460895/ASOC1617_Facsimile_formselezione_scuole.pdf)
