### ISSUE TITLE
Sezione 1 - Campi Tipologia di scuola e indirizzo specifico d'istituto

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#40]
Modificare i campi come indicato di seguito. 

Campo "Indirizzo specifico di istituto (risposta unica)" fare menu a tendina e trasferire le voci che adesso sono nel campo "Tipologia di scuola"

Campo "Tipologia di scuola", sostituire titolo con "Tipologia di istituto" e trasformare in menu a tendina con le seguenti voci: 
Istituto di Istruzione Superiore
Liceo
Istituto Tecnico 
Istituto Professionale

**Comment by sirmmo** [comment]
ok
