### ISSUE TITLE
Aggiungere menu che indichi a che punto è la compilazione e dove si è 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#42]
Puoi aggiungerlo? Quello laterale che avevamo detto che ho inserito nel template slide?

**Comment by sirmmo** [comment]
Si, stavo finendo gli elementi "strutturali".

**Comment by sirmmo** [comment]
http://www.cssscript.com/responsive-step-progress-indicator-with-pure-css/
