### ISSUE TITLE
Sezione 2 - aggiungere alla fine  domanda modalità intergrazione nella didattica

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#43]
Testo: Modalità con cui si ha intenzione di integrare progetto ASOC nella didattica (menu a tendina) 
Didattica ordinaria 	
Didattica extracurricolare
Progetto di Alternanza Scuola Lavoro

**Comment by sirmmo** [comment]
scomparsa per una svista.
