### ISSUE TITLE
Sezione 4 - campo EDIC di supporto 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOCFront#56]
Non c'è elenco nel menu a tendina (di seguito quello aggiornato) 

[A Scuola di OpenCoesione 2016-2017 - Candidatura Centri EDIC_8_Settembre.xlsx](https://github.com/AScuolaDiOpencoesione/ASOCFront/files/463631/A.Scuola.di.OpenCoesione.2016-2017.-.Candidatura.Centri.EDIC_8_Settembre.xlsx)

**Comment by sirmmo** [comment]
inserisco (avevamo detto di aspettare l'elenco definitivo).
